# Generated by Django 4.2.5 on 2023-09-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="date_created", new_name="created_at",
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="task", name="title", field=models.CharField(max_length=64),
        ),
    ]
